/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


/* Header for class com_sharp_ambition_mediacodecdemo_NativeBridge */

#ifndef _Included_com_sharp_ambition_mediacodecdemo_NativeBridge
#define _Included_com_sharp_ambition_mediacodecdemo_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sharp_ambition_mediacodecdemo_NativeBridge
 * Method:    yuvToBuffer
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sharp_ambition_mediacodecdemo_NativeBridge_yuvToBuffer
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_sharp_ambition_mediacodecdemo_NativeBridge
 * Method:    connect
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sharp_ambition_mediacodecdemo_NativeBridge_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sharp_ambition_mediacodecdemo_NativeBridge
 * Method:    disConnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sharp_ambition_mediacodecdemo_NativeBridge_disConnect
  (JNIEnv *, jobject);

/*
 * Class:     com_sharp_ambition_mediacodecdemo_NativeBridge
 * Method:    sendData
 * Signature: ([BIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sharp_ambition_mediacodecdemo_NativeBridge_sendData
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
