/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sharp_ambition_mediacodecdemo_NativeBridge */

#ifndef _Included_com_sharp_ambition_mediacodecdemo_NativeBridge
#define _Included_com_sharp_ambition_mediacodecdemo_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sharp_ambition_mediacodecdemo_NativeBridge
 * Method:    yuvToBuffer
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sharp_ambition_mediacodecdemo_NativeBridge_yuvToBuffer
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
